# Workflow: Checks code coverage for the project. Fails if line coverage is below the required threshold.
name: Check Coverage

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  check-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Run coverage
        run: |
          npm test -- --coverage --collectCoverageFrom='src/**/*.{ts,jsx}' --coverageReporters=json-summary

      - name: Download coverage summary
        uses: actions/download-artifact@v4
        with:
          name: coverage-summary
          path: coverage

      - name: Check coverage threshold
        shell: bash
        run: |
          coverageValue=$(jq -r '.total.lines.pct' coverage/coverage-summary.json)
          echo "Line Coverage: $coverageValue%"
          if (( $(echo "$coverageValue < 90" | bc -l) )); then
            echo "##[error]Line coverage is below 90%"
            exit 1
          fi

      - name: Comment coverage threshold on PR
        run: |
          PR=$(jq -r .pull_request.number $GITHUB_EVENT_PATH)
          BODY="## Coverage Threshold\n\nLine Coverage: $coverageValue%"
          CID=$(gh api repos/${{ github.repository }}/issues/$PR/comments --jq '.[] | select(.body|contains(\"## Coverage Threshold\")) | .id' | head -n1)
          if [ -n "$CID" ]; then
            gh api repos/${{ github.repository }}/issues/comments/$CID -X PATCH -f body="$BODY"
          else
            gh api repos/${{ github.repository }}/issues/$PR/comments -f body="$BODY"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
