name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  NPM_TOKEN: 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
  GH_TOKEN: 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
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: setup semantic-release
        run: npm install -g semantic-release @semantic-release/github @semantic-release/changelog conventional-changelog-conventionalcommits @semantic-release/commit-analyzer @semantic-release/git
      - name: release
        run: semantic-release
